version: 2.1

references:
    container_config: &container_config
        docker:
            - image: circleci/android:api-29

        working_directory: ~/data

        environment:
            JVM_OPTS: -Xmx3g

commands:
    generate-gradle-checksums:
        steps:
            - run:
                  name: Generate Gradle checksums
                  command: |
                      # This finds all *.kt files and generates checksums for caching
                      find buildSrc -name "*.kt" -type f | sort | xargs shasum  > gradle-checksums.txt
                      cat gradle-checksums.txt
    restore-gradle-cache:
        description: Restore the cache of ~/.gradle based on the local build files.
        steps:
            - generate-gradle-checksums
            - restore_cache:
                  keys:
                      - gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle-checksums.txt" }}
                      - gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-
    save-gradle-cache:
        description: Cache the contents of ~/.gradle based on the local build files.
        steps:
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "gradle-checksums.txt" }}

jobs:
    update_dependency_cache:
        <<: *container_config
        steps:
            - checkout
            - restore-gradle-cache
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save-gradle-cache

    ktlint:
        <<: *container_config
        steps:
            - checkout
            - restore-gradle-cache
            - run: ./gradlew ktlintCheck
    detekt:
        <<: *container_config
        steps:
            - checkout
            - restore-gradle-cache
            - run: ./gradlew detekt

    lint:
        <<: *container_config
        steps:
            - checkout
            - restore-gradle-cache
            - run: ./gradlew lintDebug

    unit_test:
        <<: *container_config
        steps:
            - checkout
            - restore-gradle-cache
            - run: ./gradlew testDebugUnitTest

    build_app:
        description: An executor with sensible defaults for Android Gradle tasks (set with GRADLE_OPTS).

        <<: *container_config

        environment:
            GRADLE_OPTS: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

        steps:
            - checkout
            - restore-gradle-cache
            - run: ./gradlew :app:bundleDebug
workflows:
    version: 2
    verify_code:
        jobs:
            - update_dependency_cache
            - lint:
                  requires:
                      - update_dependency_cache
            - detekt:
                  requires:
                      - update_dependency_cache
            - ktlint:
                  requires:
                      - update_dependency_cache
            - unit_test:
                  requires:
                      - update_dependency_cache
            - build_app:
                  requires:
                      - lint
                      - detekt
                      - ktlint
                      - unit_test
