version: 2.1

references:
    container_config: &container_config
        docker:
            - image: circleci/android:api-29

        working_directory: ~/data

        environment:
            JVM_OPTS: -Xmx3g

jobs:
    update_dependency_cache:
        <<: *container_config
        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}

    ktlint:
        <<: *container_config
        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew ktlintCheck
    detekt:
        <<: *container_config
        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew detekt

    lint:
        <<: *container_config
        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew lint --no-parallel

    unit_test:
        <<: *container_config
        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew testDebugUnitTest

    build_app:
        description: An executor with sensible defaults for Android Gradle tasks (set with GRADLE_OPTS).

        <<: *container_config

        environment:
            GRADLE_OPTS: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew :app:bundleDebug
workflows:
    version: 2
    verify_code:
        jobs:
            - update_dependency_cache
            - lint:
                  requires:
                      - update_dependency_cache
            - detekt:
                  requires:
                      - update_dependency_cache
            - ktlint:
                  requires:
                      - update_dependency_cache
            - unit_test:
                  requires:
                      - update_dependency_cache
            - build_app:
                  requires:
                      - lint
                      - detekt
                      - ktlint
                      - unit_test
