version: 2.1

jobs:
    prepare_dependencies:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}

    ktlint:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew ktlintCheck
    detekt:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew detekt

    lint:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew lint --no-parallel

    test:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew testDebugUnitTest

    build:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew :app:bundleDebug
workflows:
    version: 2
    build_and_check:
        jobs:
            - prepare_dependencies
            - lint:
                  requires:
                      - prepare_dependencies
            - detekt:
                  requires:
                      - prepare_dependencies
            - ktlint:
                  requires:
                      - prepare_dependencies
            - test:
                  requires:
                      - prepare_dependencies
            - build:
                  requires:
                      - lint
                      - detekt
                      - ktlint
                      - test
