name: build debug

on:
  push:
    branches: [master] # Just in case master was not up to date while merging PR
  pull_request:
    types: [opened, synchronize]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build App
        run: ./gradlew :app:assembleDebug --no-build-cache

      - uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk